Dockerize knic-jupyter instance
usc-isi-i2/knic-jupyter pull request #22
Opened 2024-04-17 11:41 UTC by Dexter2389

2024-04-17 18:48 UTC, aphedges requested changes

2024-04-17 18:48 UTC, aphedges commented on Dockerfile
> +FROM nikolaik/python-nodejs:python3.11-nodejs20-slim-canary
What is the source of this image? Is it trustworthy? It might make more sense to just install Python or NodeJS in an official image.

2024-04-17 18:48 UTC, aphedges commented on Dockerfile
> +# TODO: Use the ENGINE_URL_ARG and inject it to index.ts before performing pip install
This should be resolved.

2024-04-17 19:14 UTC, Dexter2389 commented on Dockerfile
> +FROM nikolaik/python-nodejs:python3.11-nodejs20-slim-canary
I mean it has more than 10M+ pulls

2024-04-17 19:16 UTC, Dexter2389 commented on Dockerfile
> +# TODO: Use the ENGINE_URL_ARG and inject it to index.ts before performing pip install
Done

2024-04-17 23:33 UTC, aphedges commented on Dockerfile
> +FROM nikolaik/python-nodejs:python3.11-nodejs20-slim-canary
I guess that's good enough for now. We can optimizing building later, if desired.

2024-04-24 21:42 UTC, aphedges approved these changes
Looks good to me!

2024-04-24 21:42 UTC, merged